livox_node:
  frame_id: "livox_frame"
  publish_freq: 10.0          # Hz
  buffer_frames: 10           # number of frames to buffer
  integration_time_ms: 100    # ms
  flip_yz: true              # coordinate system flip option
