preprocess_node:
  # ROI フィルタパラメータ
  roi:
    min_x: 0.5
    max_x: 20.0
    min_y: -5.0
    max_y: 5.0
    min_z: -2.0
    max_z: 5.0

  # ボクセルフィルタパラメータ
  voxel:
    leaf_size: 0.05    # メートル

  # 統計的外れ値除去フィルタパラメータ
  sor:
    mean_k: 50
    std_dev_mul: 1.0
